basePath: /csat/rest
definitions:
  models.Survey:
    type: object
host: localhost:8000
info:
  contact: {}
  description: Your Microservice API with Swagger documentation
  title: Your Microservice API
  version: "1.0"
paths:
  /api/survey:
    post:
      consumes:
      - application/json
      description: Create Survey
      parameters:
      - description: Create Survey Request
        in: body
        name: request
        schema:
          $ref: '#/definitions/models.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: 'Survey Createed Successfully" example:"{''message'': ''Survey
            Createed Successfully''}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Invalid request" example:"{''error'': ''Invalid request''}'
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'Unauthorized: Token is missing or invalid" example:"{''error'':
            ''Unauthorized''}'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 'Internal server error" example:"{''error'': ''Internal server
            error''}'
          schema:
            additionalProperties: true
            type: object
      summary: Create Survey
      tags:
      - Survey
  /api/survey-details:
    get:
      consumes:
      - application/json
      description: Retrieve survey details based on Survey ID
      parameters:
      - default: 2
        description: Survey ID (required)
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Survey details retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'Unauthorized: Token is missing or invalid'
          schema:
            additionalProperties: true
            type: object
        "404":
          description: No user found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get Survey Details
      tags:
      - survey
  /api/template-details:
    get:
      consumes:
      - application/json
      description: Retrieve template details based on Template ID
      parameters:
      - default: 2
        description: Template ID (required)
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Template details retrieved successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 'Unauthorized: Token is missing or invalid'
          schema:
            additionalProperties: true
            type: object
        "404":
          description: No user found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get Template Details
      tags:
      - Templates
swagger: "2.0"
