export const projectsData = [
  {
    id: 1,
    prjName: "Project 1",
    clientName: "Raj Kumar",
    survey_frequency_days: 3,
    teamMembers: 4,
  },
  {
    id: 2,
    prjName: "Project 2",
    clientName: "Dileep",
    survey_frequency_days: 5,
    teamMembers: 5,
  },
  {
    id: 3,
    prjName: "Project 3",
    clientName: "Nandini",
    survey_frequency_days: 2,
    teamMembers: 5,
  },
  {
    id: 4,
    prjName: "Project 4",
    clientName: "Silambu",
    survey_frequency_days: 3,
    teamMembers: 4,
  },
  {
    id: 5,
    prjName: "Project 5",
    clientName: "Sandeep",
    survey_frequency_days: 7,
    teamMembers: 4,
  },
  {
    id: 6,
    prjName: "Project 6",
    clientName: "Rahul Sharma",
    survey_frequency_days: 4,
    teamMembers: 2,
  },
  {
    id: 7,
    prjName: "Project 7",
    clientName: "Naveen",
    survey_frequency_days: 3,
    teamMembers: 4,
  },
];
